2024-09-20 15:14:17,073 INFO    StreamThr :13174 [internal.py:wandb_internal():89] W&B internal server running at pid: 13174, started at: 2024-09-20 15:14:17.073239
2024-09-20 15:14:17,084 DEBUG   HandlerThread:13174 [handler.py:handle_request():144] handle_request: status
2024-09-20 15:14:17,088 INFO    WriterThread:13174 [datastore.py:open_for_write():85] open: /home/scout/catkin_ws/src/gps_nav/GPS/wandb/run-20240920_151417-c4d9etg8/run-c4d9etg8.wandb
2024-09-20 15:14:17,089 DEBUG   SenderThread:13174 [sender.py:send():375] send: header
2024-09-20 15:14:17,096 DEBUG   SenderThread:13174 [sender.py:send():375] send: run
2024-09-20 15:14:18,096 INFO    HandlerThread:13174 [handler.py:finish():845] shutting down handler
2024-09-20 15:14:18,096 INFO    WriterThread:13174 [datastore.py:close():298] close: /home/scout/catkin_ws/src/gps_nav/GPS/wandb/run-20240920_151417-c4d9etg8/run-c4d9etg8.wandb
2024-09-20 15:14:18,097 ERROR   StreamThr :13174 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/internal.py", line 328, in _process
    self._sm.send(record)
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 382, in send
    send_handler(record)
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 939, in send_run
    self._config_save(config_value_dict)
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/internal/sender.py", line 897, in _config_save
    config_util.save_config_file_from_dict(config_path, config_value_dict)
  File "/home/scout/.local/lib/python3.6/site-packages/wandb/sdk/lib/config_util.py", line 90, in save_config_file_from_dict
    sort_keys=False,
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
